<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-F4KG0T8" failures="1" tests="4" name="Test1" time="35.66" errors="0" timestamp="2024-07-04T01:25:38 IST">
  <testcase classname="testCases.Login" name="ValidatelogIn" time="7.63"/>
  <testcase classname="testCases.Login" name="InvalidlogIn" time="0.049">
    <skipped/>
  </testcase> <!-- InvalidlogIn -->
  <testcase classname="testCases.Login" name="InvalidlogIn" time="0.038">
    <skipped/>
  </testcase> <!-- InvalidlogIn -->
  <testcase classname="testCases.Login" name="InvalidlogIn" time="0.045">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at testCases.Login.InvalidlogIn(Login.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- InvalidlogIn -->
</testsuite> <!-- Test1 -->
